specVersion: "1.0.0"

name: "near-subql-starter"
version: "0.0.1"
runner:
  node:
    name: "@subql/node-near"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: "This project can be use as a starting point for developing your new Avalanche SubQuery project"
repository: "https://github.com/subquery/avalanche-subql-starter"

schema:
  file: "./schema.graphql"

network:
  endpoint: "https://archival-rpc.mainnet.near.org"
  chainId: "mainnet"

dataSources:
  - kind: near/Runtime
    startBlock: 80980000
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleBlock
          kind: near/BlockHandler
          filter:
            modulo: 10
        - handler: handleTransaction
          kind: near/TransactionHandler
          filter:
            sender: sweat_welcome.near
            receiver: token.sweat

        - handler: handleAction
          kind: near/ActionHandler
          filter:
            type: Transfer
            action:
              deposit: '50000000000000000000000'