specVersion: 1.0.0

name: near_priceoracle_example
version: 0.0.1
runner:
  node:
    name: "@subql/node-near"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: "This is an example project that indexes price oracle feeds from the NEAR blockchain using SubQuery"
repository: "https://github.com/subquery/near_priceoracle_example"

schema:
  file: ./schema.graphql

network:
  chainId: mainnet
  # This endpoint must be a public non-pruned archive node
  # Public nodes may be rate limited, which can affect indexing speed
  # When developing your project we suggest getting a private API key from a commercial provider
  endpoint: https://archival-rpc.mainnet.near.org
  # Optionally provide the HTTP endpoint of a full chain dictionary to speed up processing
  dictionary: https://api.subquery.network/sq/subquery/near-dictionary
  bypassBlocks: [81003306] # This is a missing block from the NEAR mainnet chain that we are skipping
dataSources:
  - kind: near/Runtime
    startBlock: 50838152 # You can set any start block you want here. This block was when app.nearcrowd.near was created https://nearblocks.io/txns/6rq4BNMpr8RwxKjfGYbruHhrL1ETbNzeFwcppGwZoQBY
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleNewOracle
          kind: near/ActionHandler
          filter:
            type: FunctionCall
            methodName: add_oracle
            receiver: priceoracle.near
        - handler: handleNewPrice
          kind: near/ActionHandler
          filter:
            type: FunctionCall
            methodName: report_prices
            receiver: priceoracle.near
